package com.mudita.mail.ui.util.stringKey

enum class StringKey {

    PROVIDER__GMAIL_NAME,
    PROVIDER__GMAIL_DESCRIPTION,

    PROVIDER__ICLOUD_NAME,
    PROVIDER__ICLOUD_DESCRIPTION,

    PROVIDER__OUTLOOK_NAME,
    PROVIDER__OUTLOOK_DESCRIPTION,

    PROVIDER__SETUP_MANUALLY_NAME,
    PROVIDER__SETUP_MANUALLY_DESCRIPTION
}
