name: "Rerun test and report"
on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: "Run test and generate coverage"
      run: ./gradlew -PtestCoverage jacocoTestReport -PgClientId=testClientId -PgRedirectUrl=testRedirectUrl -PgRedirectScheme=testRedirectScheme -PoClientId=testClientId -PoRedirectUrl=testRedirectUrl -PoRedirectScheme=testRedirectScheme -PoHost=testHost
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        directory: build/reports/

